ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from graphene_django.views import GraphQLView
from ecommerce.views import homepage
from api.router import urls as api_urls

urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('users.urls')),
    path('', include('likes.urls')),
    path('', include('orders.urls')),
    path('api/', include(api_urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api-auth/', include('rest_framework.urls')),
    path('graphql/', GraphQLView.as_view(graphiql=True))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/likes/urls.py
from django.urls import path
from likes.views import like_object

app_name = 'likes'

urlpatterns = [
    path('<str:model_type>/<int:object_id>/like', like_object, name='like')
]

ecommerce/orders/urls.py
from django.urls import path
from orders.views import get_all_cards, add_card, order, process_payment

app_name = 'orders'

urlpatterns = [
    path('cards/', get_all_cards, name='cards'),
    path('cards/add', add_card, name='add_card'),
    path('order/', order, name='order'),
    path('orders/<int:order_id>/process/', process_payment, name='process')
]

ecommerce/products/urls.py
from django.urls import path
from products.views import get_all_products, get_product

app_name = 'products'

urlpatterns = [
    path('', get_all_products, name='all_products'),
    path('<int:product_id>/', get_product, name='product_details'),
]

ecommerce/likes/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='likes')  # user.likes
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        related_name='likes',
    )  # content_type.likes
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')


class LikeableModel(models.Model):
    class Meta:
        abstract = True

    likes = GenericRelation(Like)

ecommerce/products/models.py
from django.db import models
from django.conf import settings
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _
from likes.models import LikeableModel


class Category(models.Model):
    class Meta:
        verbose_name_plural = _('categories')
        ordering = ('-id',)

    name = models.CharField(max_length=128, unique=True, null=False, blank=False)

    def __str__(self):
        return f'{self.name} ({self.id})'


class Store(LikeableModel):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='stores')
    name = models.CharField(max_length=128, unique=True, null=False, blank=False)
    logo = models.ImageField(upload_to='stores/', null=True, default=None)

    def __str__(self):
        return f'{self.name} ({self.id})'


class Product(LikeableModel):
    class Meta:
        ordering = ('name',)

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        default=None,
        related_name='products'
    )  # category.products
    store = models.ForeignKey(
        Store,
        on_delete=models.CASCADE,
        related_name='products'
    )  # store.products
    name = models.CharField(max_length=255, unique=True)
    normal_price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        default=0.00
    )  # 999999,99
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        default=0.00
    )  # 999999,99
    processor_owner = models.CharField(max_length=255)
    cores_number = models.IntegerField(default=1)
    processor_technology = models.IntegerField(default=None, null=True)
    memory_capacity = models.IntegerField(default=None, null=True)
    memory_type = models.CharField(max_length=255, default=None, null=True)
    hdd_type = models.CharField(max_length=255, default=None, null=True)
    weight = models.DecimalField(max_digits=8, decimal_places=2, default=None, null=True)
    stock = models.IntegerField(default=0)
    image = models.ImageField(upload_to='products/', default=None, null=True)

    @property
    def image_url(self):
        if self.image:
            return self.image.url

        return static('images/defaultProductImage.png')

    def __str__(self):
        return f'{self.name} ({self.id})'

ecommerce/products/forms.py
from django import forms


class CartForm(forms.Form):
    quantity = forms.IntegerField(required=True, label="", initial=0, min_value=0)

    def __init__(self, *args, product=None, session=None, **kwargs):
        # if 'product' in kwargs:
        #     self._product = kwargs.pop('product')
        # else:
        #     self._product = None
        #
        # if 'session' in kwargs:
        #     self._session = kwargs.pop('session')
        # else:
        #     self._session = None
        super().__init__(*args, **kwargs)

        self._product = product
        self._session = session

    def save(self):
        # add Product with ID = <product_id> to cart in quantity = <quantity>
        quantity = self.cleaned_data['quantity']

        # if 'cart' in self._session:
        #     self._session['cart'][self._product.id] = quantity
        # else:
        #     self._session['cart'] = {
        #         self._product.id: quantity
        #     }
        if 'cart' not in self._session:
            self._session['cart'] = {}

        old_quantity = self._session['cart'].get(str(self._product.id), 0)
        self._session['cart'][self._product.id] = quantity + old_quantity
        self._session.modified = True

ecommerce/products/forms/cart.py
from django import forms


class CartForm(forms.Form):
    quantity = forms.IntegerField(required=True, label="", initial=0, min_value=0)

    def __init__(self, *args, product=None, session=None, **kwargs):
        # if 'product' in kwargs:
        #     self._product = kwargs.pop('product')
        # else:
        #     self._product = None
        #
        # if 'session' in kwargs:
        #     self._session = kwargs.pop('session')
        # else:
        #     self._session = None
        super().__init__(*args, **kwargs)

        self._product = product
        self._session = session

    def save(self):
        # add Product with ID = <product_id> to cart in quantity = <quantity>
        quantity = self.cleaned_data['quantity']

        # if 'cart' in self._session:
        #     self._session['cart'][self._product.id] = quantity
        # else:
        #     self._session['cart'] = {
        #         self._product.id: quantity
        #     }
        if 'cart' not in self._session:
            self._session['cart'] = {}

        old_quantity = self._session['cart'].get(str(self._product.id), 0)
        self._session['cart'][self._product.id] = quantity + old_quantity
        self._session.modified = True

ecommerce/products/forms/filter.py
from enum import Enum
from django import forms
from products.models import Product, Store, Category


class SearchAndFilterForm(forms.Form):
    order_by_choices = (
        ('price_asc', 'Price ascending'),
        ('price_desc', 'Price descending'),
    )

    category = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, required=False, choices=())
    name = forms.CharField(max_length=255, required=False)
    price_min = forms.IntegerField(min_value=0, required=False)
    price_max = forms.IntegerField(min_value=0, required=False)
    order_by = forms.ChoiceField(widget=forms.Select, choices=order_by_choices, required=False)
    memory_capacity = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, required=False, choices=())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        available_memory_capacity = set(product.memory_capacity for product in Product.objects.all())
        self.fields['memory_capacity'].choices = (
            (data, f'{data} GB') for data in available_memory_capacity
        )
        self.fields['category'].choices = (
            (category.id, category.name)
            for category in Category.objects.all()
        )

    def get_results(self):
        name = self.cleaned_data.get('name')
        category_ids = self.cleaned_data.get('category')
        price_min = self.cleaned_data.get('price_min')
        price_max = self.cleaned_data.get('price_max')
        order_by = self.cleaned_data.get('order_by')
        memory_capacity = self.cleaned_data.get('memory_capacity')

        if order_by == 'price_asc':
            products = Product.objects.order_by('price')
        else:
            products = Product.objects.order_by('-price')

        if name:
            products = products.filter(name__icontains=name)

        if price_min:
            products = products.filter(price__gte=price_min)

        if price_max:
            products = products.filter(price__lte=price_max)

        if len(category_ids) > 0:
            products = products.filter(category__id__in=category_ids)

        if len(memory_capacity) > 0:
            products = products.filter(memory_capacity__in=memory_capacity)

        return products.all()

ecommerce/likes/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404, Http404
from products.models import Product, Store
from likes.models import Like


def like_object(request, model_type, object_id):
    if request.method != 'POST':
        raise Http404('This method is not supported.')

    if model_type == 'products':
        my_model = Product
        redirect_url = reverse('products:product_details', kwargs={'product_id': object_id})
    elif model_type == 'stores':
        my_model = Store
        redirect_url = reverse('stores:store_details', kwargs={'store_id': object_id})
    else:
        raise Http404('Object is not likeable.')

    likeable_object = get_object_or_404(my_model, pk=object_id)
    like = likeable_object.likes.filter(user=request.user).first()
    if like is None:
        Like.objects.create(
            user=request.user,
            content_object=likeable_object
        )
    else:
        like.delete()

    print('\n' * 2)
    print('model_type', model_type)
    print('object_id', object_id)
    print('\n' * 2)
    # return redirect(reverse('??', kwargs={'??': object_id}))

    return redirect(redirect_url)

ecommerce/products/views.py
from django.shortcuts import render, HttpResponse, Http404

products = [
    {
        "id": index,
        "name": f"Product #{index}"
    } for index in range(1, 61)
]


# Create your views here.
def get_all_products(request):
    return render(request, 'products.html', {
        "products": products
    })


def get_product(request, product_id):
    try:
        product = [p for p in products if p["id"] == product_id][0]
    except IndexError:
        raise Http404('This product is not available.')

    return render(request, 'product.html', {
        "product": product
    })

ecommerce/products/views/cart.py
from django.shortcuts import render
from products.models import Product
from helpers.cart import get_total_price


def get_cart(request):
    cart_product_ids = request.session.get('cart', {}).keys()
    products = Product.objects.filter(id__in=cart_product_ids).all()
    total_price = get_total_price(request.session.get('cart', {}), products)

    return render(request, 'products/cart.html', {
        'products': products,
        'total_price': total_price,
    })

ecommerce/products/views/categories.py
from django.shortcuts import render
from products.models import Category


def get_all_categories(request):
    categories = Category.objects.all()

    return render(request, 'products/categories.html', {
        'categories': categories
    })

ecommerce/products/views/products.py
from django.shortcuts import render, Http404, get_object_or_404, redirect, reverse
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from products.models import Product
from products.forms.cart import CartForm
from products.forms.filter import SearchAndFilterForm
from likes.models import Like


def get_all_products(request):
    filter_form = SearchAndFilterForm(request.GET)
    if filter_form.is_valid():
        products = filter_form.get_results()
    else:
        raise Http404('Search and filter form is invalid!')

    paginator = Paginator(products, 6)  # use 6 products per each page.

    page = request.GET.get('page', 1)
    products_page = paginator.get_page(page)

    cart_form = CartForm()

    return render(request, 'products/products.html', {
        "products_page": products_page,
        "cart_form": cart_form,
        "filter_form": filter_form,
        "total_products": len(products)
    })


def get_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    return render(request, 'products/product.html', {
        "product": product
    })


def add_to_cart(request, product_id):
    if request.method == 'GET':
        raise Http404('Method not allowed.')

    product = get_object_or_404(Product, pk=product_id)

    form = CartForm(request.POST, product=product, session=request.session)

    if form.is_valid():
        form.save()

        quantity = form.cleaned_data["quantity"]
        messages.success(request, f'Product {product.name} was added to cart {quantity} times.')
    else:
        messages.error(request, f'Product {product.name} was not added to cart.')

    page = request.GET.get('page')
    return redirect(f"{reverse('products:all_products')}?page={page}")  # products/?page=<page_number>


@login_required
def like_product(request, product_id):
    if request.method != 'POST':
        raise Http404('This method is not supported.')

    product = get_object_or_404(Product, pk=product_id)
    like = product.likes.filter(user=request.user).first()
    if like is None:
        Like.objects.create(
            user=request.user,
            content_object=product
        )
    else:
        like.delete()

    return redirect(reverse('products:product_details', kwargs={'product_id': product.id}))

ecommerce/products/views/stores.py
from django.shortcuts import render, Http404, get_object_or_404, redirect, reverse
from django.contrib.auth.decorators import login_required
from products.models import Store
from likes.models import Like


def get_all_stores(request):
    stores = Store.objects.all()

    return render(request, 'products/stores.html', {
        'stores': stores
    })


def get_store(request, store_id):
    # store = Store.objects.filter(id=store_id).first()
    # try:
    #     store = Store.objects.get(id=store_id)
    # except Store.DoesNotExist:
    #     raise Http404('Unavailable store.')
    store = get_object_or_404(Store, id=store_id)

    return render(request, 'products/store.html', {
        'store': store
    })


@login_required
def like_store(request, store_id):
    if request.method != 'POST':
        raise Http404('This method is not supported.')

    store = get_object_or_404(Store, pk=store_id)
    like = store.likes.filter(user=request.user).first()
    if like is None:
        Like.objects.create(
            user=request.user,
            content_object=store
        )
    else:
        like.delete()

    return redirect(reverse('stores:store_details', kwargs={'store_id': store.id}))

ecommerce/products/templates/products/cart.html
{% extends 'base.html' %}
{% load cart %}

{% block title %}Cart{% endblock %}

{% block content %}
    <h1>Cart page</h1>
    {% if products|length == 0 %}
        <p>You don't have any products in your cart.</p>
    {% else %}
        <ul>
            {% for product in products %}
                <li>
                    <p>
                        Product: {{ product.name }}
                    </p>
                    <p>
                        Quantity: {{ request.session.cart | product_qty:product.id }}
                    </p>
                </li>
            {% endfor %}
        </ul>
        <p>
            <strong>Total price:</strong> {{ total_price }} RON
        </p>
        <form method="post" action="{% url 'orders:order' %}">
            {% csrf_token %}
            <input type="submit" value="Order" />
        </form>
    {% endif %}
{% endblock %}

ecommerce/products/templates/products/cart_link.html
<a href="{% url 'cart' %}" title="Total price {{ price }} RON">
    Cart ({{ products }})
</a>

ecommerce/products/templates/products/categories.html
{% extends 'base.html' %}

{% block title %}Categories{% endblock %}

{% block content %}
    <ul>
        {% for category in categories %}
            <li>{{ category.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

ecommerce/products/templates/products/like_form.html
<p>
    <strong>Likes:</strong> {{ likes }}
</p>
{% if is_authenticated %}
    <p>
        <form method="post" action="{{ path }}">
            {% csrf_token %}
            <input type="submit" value="Like/Unlike"/>
        </form>
    </p>
{% endif %}

ecommerce/products/templates/products/product.html
{% extends 'base.html' %}
{% load cart %}

{% block page_title %}Product page{% endblock %}

{% block content %}
    <img src="{{ product.image_url }}" width="200"/>
    <strong>Name: </strong> {{ product.name }}
    {% url 'likes:like' 'products' product.id as like_route %}
    {% like_form product like_route %}
{% endblock %}

ecommerce/products/templates/products/products.html
{% extends 'base.html' %}

{% block page_title %}Products page{% endblock %}

{% block content %}
    <h1>Available products ({{ total_products }})</h1>
    <form method="get" action="{% url 'products:all_products' %}">
        {% csrf_token %}
        {{ filter_form.as_p }}
        <input type="submit" value="Apply filters" />
    </form>
    <ul style="list-style-type: none; padding: 0; margin: 0; display: flex; flex-wrap: wrap;">
        {% for product in products_page %}
            <li style="width: 50%;">
                <img src="{{ product.image_url }}" width="100"/>
                <p>
                    <strong>Price:</strong> {{ product.price }}
                </p>
                <p>
                    <strong>Name:</strong> {{ product.name }}
                </p>
                <a href="{% url 'products:product_details' product.id %}">View details</a>
                <div>
                    <form method="post"
                          action="{% url 'products:add_to_cart' product.id %}?page={{ products_page.number }}">
                        {% csrf_token %}
                        {{ cart_form }}
                        <input type="submit" value="Add to Cart"/>
                    </form>
                </div>
            </li>
        {% endfor %}
    </ul>
    <p>
        Page {{ products_page.number }} / {{ products_page.paginator.num_pages }} |
        <a href="{% url 'products:all_products' %}?page=1">First page</a> |
        {% if products_page.has_previous %}
            <a href="{% url 'products:all_products' %}?page={{ products_page.previous_page_number }}">Previous page</a>
            |
        {% endif %}
        {% if products_page.has_next %}
            <a href="{% url 'products:all_products' %}?page={{ products_page.next_page_number }}">Next page</a> |
        {% endif %}
        <a href="{% url 'products:all_products' %}?page={{ products_page.paginator.num_pages }}">Last page</a>
    </p>
{% endblock %}

ecommerce/products/templates/products/store.html
{% extends 'base.html' %}
{% load cart %}

{% block page_title %}Store {{ store.name }}{% endblock %}

{% block content %}
    <h1>{{ store.name }}</h1>
    <p>
        <strong>Owner:</strong>
        {{ store.owner.first_name }} {{ store.owner.last_name }}
    </p>
    <p>
        <strong>Contact:</strong>
        {{ store.owner.email }}
    </p>
    {% url 'likes:like' 'stores' store.id as like_route %}
    {% like_form store like_route %}
{% endblock %}

ecommerce/products/templates/products/stores.html
{% extends 'base.html' %}

{% block page_title %}Stores page{% endblock %}

{% block content %}
    <h1>Available stores</h1>
    <ul>
        {% for store in stores %}
            <li>
                <p>
                    <strong>Name:</strong>
                    {{ store.name }}
                </p>
                <p>
                    <strong>Owner:</strong>
                    {{ store.owner.first_name }} {{ store.owner.last_name }} ({{ store.owner.email }})
                </p>
                <a href="{% url 'stores:store_details' store.id %}">View details</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}