ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from graphene_django.views import GraphQLView
from ecommerce.views import homepage
from api.router import urls as api_urls

urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('users.urls')),
    path('', include('likes.urls')),
    path('', include('orders.urls')),
    path('api/', include(api_urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api-auth/', include('rest_framework.urls')),
    path('graphql/', GraphQLView.as_view(graphiql=True))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/likes/urls.py
from django.urls import path
from likes.views import like_object

app_name = 'likes'

urlpatterns = [
    path('<str:model_type>/<int:object_id>/like', like_object, name='like')
]

ecommerce/orders/urls.py
from django.urls import path
from orders.views import get_all_cards, add_card, order, process_payment

app_name = 'orders'

urlpatterns = [
    path('cards/', get_all_cards, name='cards'),
    path('cards/add', add_card, name='add_card'),
    path('order/', order, name='order'),
    path('orders/<int:order_id>/process/', process_payment, name='process')
]

ecommerce/orders/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator
from products.models import Product


class Order(models.Model):
    class StatusChoices(models.IntegerChoices):
        PENDING = 0
        COMPLETE = 1
        INCOMPLETE = 2

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, default=None)
    billing_address = models.CharField(max_length=256, null=True, default=None)
    shipping_address = models.CharField(max_length=256, null=True, default=None)
    status = models.IntegerField(choices=StatusChoices.choices, default=0, null=False)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET, null=True, default=None)
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        default=0.00,
        validators=(MinValueValidator(0.00),)
    )  # 999999,99
    quantity = models.IntegerField(default=1, validators=(MinValueValidator(1),))


class StripeCustomer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='stripe_customer')
    stripe_id = models.CharField(max_length=256, null=False)


class StripeCard(models.Model):
    stripe_customer = models.ForeignKey(StripeCustomer, on_delete=models.CASCADE, related_name='cards')
    stripe_id = models.CharField(max_length=256, null=False)
    brand = models.CharField(max_length=20, null=True, default=None)
    last4 = models.CharField(max_length=4, null=True, default=None)
    exp_month = models.IntegerField(null=True, default=None)
    exp_year = models.IntegerField(null=True, default=None)

    def __str__(self):
        return f'**** **** **** {self.last4}'

ecommerce/orders/forms.py
from django import forms
from orders.models import Order, OrderItem
from orders.models import StripeCard


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['user', 'status']

    card = forms.ChoiceField(
        widget=forms.RadioSelect,
        label='Card',
        choices=(),
    )

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop('user')
        self._cart_data = kwargs.pop('cart_data')
        self._products = kwargs.pop('products')

        super().__init__(*args, **kwargs)

        self.fields['card'].choices = (
            (card.id, str(card))
            for card in StripeCard.objects.filter(stripe_customer=self._user.stripe_customer).all()
        )

    def clean_card(self):
        card_id = self.cleaned_data['card']

        print('card', card_id)
        try:
            stripe_card = StripeCard.objects.get(pk=card_id, stripe_customer=self._user.stripe_customer)
        except StripeCard.DoesNotExist:
            stripe_card = None

        if not stripe_card:
            raise forms.ValidationError('Invalid card.')

        return stripe_card

    def save(self, commit=True):
        order = super().save(commit=False)
        order.user = self._user

        order_items = []
        for product in self._products:
            order_items.append(
                OrderItem(
                    order=order,
                    product=product,
                    price=product.price,
                    quantity=self._cart_data.get(str(product.id))
                )
            )

        if commit is True:
            order.save()

            for order_item in order_items:
                order_item.save()

        return order

ecommerce/orders/views.py
import stripe
from django.shortcuts import render, Http404, redirect, reverse, get_object_or_404, HttpResponse
from django.conf import settings
from django.contrib import messages
from orders.models import StripeCard, Order
from products.models import Product
from helpers.cart import get_total_price
from orders.forms import OrderForm


def get_all_cards(request):
    stripe_cards = StripeCard.objects.filter(stripe_customer=request.user.stripe_customer).all()

    return render(request, 'orders/cards.html', {
        'cards': stripe_cards
    })


def add_card(request):
    if request.method == 'POST':
        if 'stripe_token' not in request.POST:
            raise Http404('Stripe token not available.')

        stripe_token = request.POST['stripe_token']
        card_data = stripe.Customer.create_source(
            request.user.stripe_customer.stripe_id,
            source=stripe_token,
            api_key=settings.STRIPE_SECRET_KEY
        )

        StripeCard.objects.create(
            stripe_customer=request.user.stripe_customer,
            stripe_id=card_data['id'],
            brand=card_data['brand'],
            last4=card_data['last4'],
            exp_month=card_data['exp_month'],
            exp_year=card_data['exp_year'],
        )

        return redirect(reverse('orders:cards'))

    return render(request, 'orders/add_card.html', {
        'STRIPE_PUBLIC_KEY': settings.STRIPE_PUBLIC_KEY
    })


def order(request):
    if request.method != 'POST':
        raise Http404('Method not allowed!')

    cart_data = request.session.get('cart', {})
    cart_product_ids = cart_data.keys()
    products = Product.objects.filter(id__in=cart_product_ids)
    total_price = get_total_price(cart_data, products)

    is_card_available = request.POST.get('card')
    cart_data = request.session.get('cart', {})

    if is_card_available:
        form = OrderForm(request.POST, user=request.user, cart_data=cart_data, products=products)
        if form.is_valid():
            order = form.save()
            card = form.cleaned_data['card']
            process_payment_route = reverse('orders:process', kwargs={'order_id': order.id})

            payment_intent = stripe.PaymentIntent.create(
                amount=int(float(total_price) * 100),
                currency='ron',
                customer=request.user.stripe_customer.stripe_id,
                payment_method=card.stripe_id,
                confirm=True,
                return_url=f'{settings.CURRENT_DOMAIN}{process_payment_route}',
                api_key=settings.STRIPE_SECRET_KEY,
            )

            next_action = payment_intent.get('next_action')

            if next_action:
                return redirect(next_action['redirect_to_url']['url'])

            return redirect()
    else:
        form = OrderForm(user=request.user, cart_data=cart_data, products=products)

    return render(request, 'orders/order.html', {
        'total_price': total_price,
        'form': form,
    })


def process_payment(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    payment_intent_id = request.GET.get('payment_intent')

    if not payment_intent_id:
        raise Http404('Invalid payment intent ID.')

    payment_intent = stripe.PaymentIntent.retrieve(
        payment_intent_id,
        api_key=settings.STRIPE_SECRET_KEY
    )

    payment_error = payment_intent['last_payment_error']
    if payment_error is None:
        order.status = Order.StatusChoices.COMPLETE
        messages.success(request, 'Payment was completed.')
    else:
        order.status = Order.StatusChoices.INCOMPLETE
        messages.error(request, 'Payment was incomplete.')

    order.save()

    return redirect(reverse('homepage'))

ecommerce/orders/templates/orders/add_card.html
{% extends 'base.html' %}

{% block bodyjavascript %}
    <script src="https://js.stripe.com/v3/"></script>
    <script>
        var stripe = Stripe('{{ STRIPE_PUBLIC_KEY }}');
        var elements = stripe.elements();

        var elements = stripe.elements();
        var style = {
          base: {
            color: "#32325d",
          }
        };

        var card = elements.create("card", { style: style, hidePostalCode : true });
        card.mount("#card-element");

        // Submit the form with the token ID.
        function stripeTokenHandler(token) {
          // Insert the token ID into the form so it gets submitted to the server
          var form = document.getElementById('payment-form');
          var hiddenInput = document.createElement('input');
          hiddenInput.setAttribute('type', 'hidden');
          hiddenInput.setAttribute('name', 'stripe_token');
          hiddenInput.setAttribute('value', token.id);
          form.appendChild(hiddenInput);

          // Submit the form
          form.submit();
        }

        // Handle form submission.
        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function(event) {
          event.preventDefault();

          stripe.createToken(card).then(function(result) {
            if (result.error) {
              // Inform the user if there was an error.
              var errorElement = document.getElementById('card-errors');
              errorElement.textContent = result.error.message;
            } else {
              // Send the token to your server.
              stripeTokenHandler(result.token);
            }
          });
        });
    </script>
{% endblock %}

{% block content %}
    <h1>Add a new card</h1>
    <form id="payment-form" method="post" action="{% url 'orders:add_card' %}">
        {% csrf_token %}
        <div id="card-element">
        <!-- Elements will create input elements here -->
        </div>

        <!-- We'll put the error messages in this element -->
        <div id="card-errors" role="alert"></div>

        <button type="submit">Add card</button>
    </form>
{% endblock %}

ecommerce/orders/templates/orders/cards.html
{% extends 'base.html' %}

{% block content %}
    <h1>My saved cards</h1>

    {% if cards|length > 0 %}
        <p>You can add a card <a href="{% url 'orders:add_card' %}">here</a>.</p>
    {% endif %}

    <ul>
        {% for card in cards %}
            <li>
                <p>
                    <strong>Brand:</strong> {{ card.brand }}
                </p>
                <p>
                    <strong>Number:</strong> **** **** **** {{ card.last4 }}
                </p>
                <p>
                    <strong>Expire date:</strong> {{ card.exp_month }}/{{ card.exp_year }}
                </p>
            </li>
        {% empty %}
            <p>You don't have any cards yet. Please add a card <a href="{% url 'orders:add_card' %}">here</a>.</p>
        {% endfor %}
    </ul>
{% endblock %}

ecommerce/orders/templates/orders/order.html
{% extends 'base.html' %}

{% block content %}
    <h1>Order page</h1>
    <p>
        <strong>You will have to pay {{ total_price }} RON.</strong>
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Order"/>
    </form>
{% endblock %}