ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from graphene_django.views import GraphQLView
from ecommerce.views import homepage
from api.router import urls as api_urls

urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('users.urls')),
    path('', include('likes.urls')),
    path('', include('orders.urls')),
    path('api/', include(api_urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api-auth/', include('rest_framework.urls')),
    path('graphql/', GraphQLView.as_view(graphiql=True))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/likes/urls.py
from django.urls import path
from likes.views import like_object

app_name = 'likes'

urlpatterns = [
    path('<str:model_type>/<int:object_id>/like', like_object, name='like')
]

ecommerce/orders/urls.py
from django.urls import path
from orders.views import get_all_cards, add_card, order, process_payment

app_name = 'orders'

urlpatterns = [
    path('cards/', get_all_cards, name='cards'),
    path('cards/add', add_card, name='add_card'),
    path('order/', order, name='order'),
    path('orders/<int:order_id>/process/', process_payment, name='process')
]

ecommerce/products/urls.py
from django.urls import path
from products.views import get_all_products, get_product

app_name = 'products'

urlpatterns = [
    path('', get_all_products, name='all_products'),
    path('<int:product_id>/', get_product, name='product_details'),
]

ecommerce/users/urls.py
from django.urls import path
from users.views import login_view, register_view, logout_view, profile_view

app_name = 'users'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
]

ecommerce/templates/actions_feedback.html
{% if messages %}
    <ul class="actions-feedback">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

ecommerce/templates/base.html
{% load static %}

<html>
<head>
    <title>{% block page_title %}{% endblock %}</title>
    <style>
        body {
            margin: 0;
        }

        header {
            background-color: #eee;
            border-bottom: 1px solid #aaa;
            padding: 20px 20px;
        }

        main {
            padding: 20px 20px;
        }

        .actions-feedback .success {
            color: green;
        }

        .actions-feedback .error {
            color: red;
        }

        .actions-feedback .warning {
            color: orange;
        }
    </style>
</head>
<body>
<header>
    <div>
        <img src="{% static 'images/marketLogo.jpg' %}" width="50"/>
    </div>
    <div>
        {% include 'navigation.html' %}
    </div>
</header>
<main>
    {% include 'actions_feedback.html' %}
    {% block content %}{% endblock %}
</main>
{% block bodyjavascript %}
{% endblock %}
</body>
</html>

ecommerce/templates/homepage.html
{% extends 'base.html' %}

{% block page_title %}Homepage{% endblock %}

{% block content %}
    <h1>This is the homepage content.</h1>
{% endblock %}

ecommerce/templates/navigation.html
{% load cart %}

{% comment %}{% cart_data as my_cart %}{% endcomment %}

<nav style="display: flex; justify-content: space-between">
    <div>
        <a href="/">Homepage</a>
        <a href="{% url 'products:all_products' %}">Products</a>
        <a href="{% url 'stores:all_stores' %}">Stores</a>
        <a href="{% url 'orders:cards' %}">Cards</a>
        {% comment %}
        <a href="{% url 'cart' %}" title="Total price {{ my_cart.total_price }} RON">Cart ({{ my_cart.total_products }})</a>
        {% endcomment %}
        {% cart_link %}
    </div>
    <div>
        {% if user.is_authenticated %}
            {% if user.is_staff %}
                <a href={% url 'admin:index' %}>Admin</a>
            {% endif %}
            <a href="{% url 'users:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'users:login' %}">Login</a>
            <a href="{% url 'users:register' %}">Register</a>
        {% endif %}
    </div>
</nav>